# 项目相关配置
app:
  # 名称
  name: MustApp
  # 版本
  version: 1.0.2
  # 版权年份
  copyrightYear: 2022
  # 实例演示开关
  demoEnabled: true
  # 文件路径 示例（ Windows配置D:/home/uploadPath，Linux配置 /home/uploadPath）
  profile: /home/uploadPath
  # 获取ip地址开关
  addressEnabled: false
  # 验证码类型 math 数组计算 char 字符验证
  captchaType: math

# 代码生成
gen:
  # 作者
  author:
  # 默认生成包路径 system 需改成自己的模块名称 如 system monitor tool
  packageName: com.must.project.system
  # 自动去除表前缀，默认是true
  autoRemovePre: false
  # 表前缀（生成类名不会包含表前缀，多个用逗号分隔）
  tablePrefix: sys_

spring:
  profiles:
    active: dev